# Generated by Django 3.2.4 on 2021-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_auto_20200611_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=70, verbose_name='Emaili')),
                ('message', models.CharField(max_length=250, verbose_name='Xabari')),
            ],
        ),
    ]
