# Generated by Django 3.2.4 on 2021-08-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
