# Generated by Django 3.2.4 on 2021-08-06 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti"),
            preserve_default=False,
        ),
    ]
