# Generated by Django 4.1.6 on 2023-02-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0009_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '記事', 'verbose_name_plural': '記事'},
        ),
    ]
